# Generated by Django 4.2 on 2024-10-12 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(max_length=64, verbose_name="Имя сотрудника"),
                ),
                (
                    "lastName",
                    models.CharField(max_length=128, verbose_name="Фамилия сотрудника"),
                ),
                (
                    "role",
                    models.CharField(
                        max_length=64,
                        verbose_name="Роль сотрудника в команде (должность)",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            (1, "senior"),
                            (2, "middle+"),
                            (3, "middle"),
                            (4, "junior+"),
                            (5, "junior"),
                            (6, "intern"),
                        ],
                        max_length=10,
                        verbose_name="Идентификатор грейда сотрудника",
                    ),
                ),
                (
                    "key_employee",
                    models.BooleanField(
                        max_length=4, verbose_name="Является ли сотрудник ключевым"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        null=True,
                        upload_to="users/images/",
                        verbose_name="Ссылка на иконку сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ("lastName",),
            },
        ),
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_expertise",
                    models.CharField(
                        choices=[
                            (1, "Компетенция Разработка"),
                            (2, "Компетнция Тестирование"),
                            (3, "Компетнция Дизайн"),
                        ],
                        max_length=16,
                        verbose_name="Название компетенции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Компетенция",
                "verbose_name_plural": "Компетенции",
                "ordering": ("name_expertise",),
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_name",
                    models.CharField(max_length=32, verbose_name="Название навыка"),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[(1, "hard-skill"), (2, "soft-skill")],
                        max_length=16,
                        verbose_name="Тип навыка",
                    ),
                ),
                (
                    "id_expertise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="users_skills.expertise",
                        verbose_name="Идентификатор компетенции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
                "ordering": ("skill_name",),
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "about_team",
                    models.CharField(
                        max_length=128, verbose_name="Краткая информация о команде"
                    ),
                ),
                (
                    "url_confluence",
                    models.CharField(
                        max_length=128,
                        verbose_name="Ссылка на пространство команды в конфлюенс",
                    ),
                ),
                (
                    "url_jira",
                    models.CharField(
                        max_length=128, verbose_name="Ссылка на jira команды"
                    ),
                ),
                (
                    "product_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teams_product_owner",
                        to="users_skills.employee",
                        verbose_name="id продукт оунера",
                    ),
                ),
                (
                    "team_lead",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teams_team_lead",
                        to="users_skills.employee",
                        verbose_name="id тимлида",
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="User_s_teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rights",
                    models.CharField(
                        choices=[(0, "view"), (1, "edit")],
                        max_length=4,
                        verbose_name="Права сотрудника для работы с дашбордом команды",
                    ),
                ),
                (
                    "id_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_s_teams",
                        to="users_skills.employee",
                        verbose_name="Идентификатор сотрудника",
                    ),
                ),
                (
                    "id_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_s_teams",
                        to="users_skills.team",
                        verbose_name="Идентификатор команды",
                    ),
                ),
            ],
            options={
                "verbose_name": "Права пользователя",
                "verbose_name_plural": "Права пользователей",
                "ordering": ("id_employee",),
            },
        ),
        migrations.CreateModel(
            name="Team_s_skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_skill",
                    models.BooleanField(
                        max_length=4, verbose_name="Флаг, является ли навык ключевым"
                    ),
                ),
                (
                    "required_level",
                    models.CharField(
                        max_length=128,
                        verbose_name="Необходимый уровень владения навыком",
                    ),
                ),
                (
                    "required_count_employees",
                    models.PositiveIntegerField(
                        verbose_name="Количество сотрудников в команде,которые должны обладать навыком"
                    ),
                ),
                (
                    "id_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_s_skills",
                        to="users_skills.skill",
                        verbose_name="Идентификатор навыка",
                    ),
                ),
                (
                    "id_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_s_skills",
                        to="users_skills.team",
                        verbose_name="Идентификатор команды",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навыки команды",
                "verbose_name_plural": "Навыки команд",
                "ordering": ("id_team",),
            },
        ),
        migrations.CreateModel(
            name="Team_s_employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_s_employees",
                        to="users_skills.employee",
                        verbose_name="Идентификатор сотрудника",
                    ),
                ),
                (
                    "id_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_s_employees",
                        to="users_skills.team",
                        verbose_name="Идентификатор команды",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав команды",
                "verbose_name_plural": "Состав команд",
                "ordering": ("id_team",),
            },
        ),
        migrations.CreateModel(
            name="Skill_for_grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            (1, "senior"),
                            (2, "middle+"),
                            (3, "middle"),
                            (4, "junior+"),
                            (5, "junior"),
                            (6, "intern"),
                        ],
                        max_length=10,
                        verbose_name="Идентификатор грейда сотрудника",
                    ),
                ),
                (
                    "required_level_for_grade",
                    models.CharField(
                        max_length=16, verbose_name="Необходимый уровень для повышения"
                    ),
                ),
                (
                    "id_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_for_grades",
                        to="users_skills.skill",
                        verbose_name="Идентификатор навыка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык для грейда",
                "verbose_name_plural": "Навыки для грейда",
                "ordering": ("id_skill",),
            },
        ),
        migrations.CreateModel(
            name="Employee_skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            (1, "Экспертный"),
                            (2, "Уверенный"),
                            (3, "Базовый"),
                            (4, "Начинающий"),
                            (5, "Не владеет"),
                        ],
                        max_length=16,
                        verbose_name="Уровень владения навыком",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (0, "Не соответствует"),
                            (1, "Соответствует"),
                            (2, "В процессе развития"),
                        ],
                        max_length=64,
                        verbose_name="Статус развития навыка",
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        null=True, verbose_name="Дата изменения уровня владения навыком"
                    ),
                ),
                (
                    "id_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_skills",
                        to="users_skills.employee",
                        verbose_name="Идентификатор сотрудника",
                    ),
                ),
                (
                    "id_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_skills",
                        to="users_skills.skill",
                        verbose_name="Идентификатор навыка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык сотрудника",
                "verbose_name_plural": "Навыки сотрудников",
                "ordering": ("id",),
            },
        ),
    ]
