# Generated by Django 4.2 on 2024-10-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(1, 'Экспертный'), (2, 'Уверенный'), (3, 'Базовый'), (4, 'Начинающий'), (5, 'Не владеет')], max_length=16, verbose_name='Уровень владения навыком')),
                ('status', models.CharField(choices=[(0, 'Не соответствует'), (1, 'Соответствует'), (2, 'В процессе развития')], max_length=64, verbose_name='Статус развития навыка')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения уровня владения навыком')),
            ],
            options={
                'verbose_name': 'Навык сотрудника',
                'verbose_name_plural': 'Навыки сотрудников',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='grade',
            field=models.CharField(choices=[(1, 'Senior'), (2, 'Middle+'), (3, 'Middle'), (4, 'Junior+'), (5, 'Junior'), (6, 'Intern')], max_length=10, verbose_name='Идентификатор грейда сотрудника'),
        ),
        migrations.AlterField(
            model_name='skill_for_grade',
            name='grade',
            field=models.CharField(choices=[(1, 'Senior'), (2, 'Middle+'), (3, 'Middle'), (4, 'Junior+'), (5, 'Junior'), (6, 'Intern')], max_length=10, verbose_name='Идентификатор грейда сотрудника'),
        ),
        migrations.DeleteModel(
            name='Employee_skill',
        ),
        migrations.AddField(
            model_name='employee_skills',
            name='id_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='users_skills.employee', verbose_name='Идентификатор сотрудника'),
        ),
        migrations.AddField(
            model_name='employee_skills',
            name='id_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='users_skills.skill', verbose_name='Идентификатор навыка'),
        ),
    ]
