import type { Metadata } from 'next';
import { manrope } from '@/source/app/fonts/fonts';
import '@/source/app/styles/global.css';
// import './globals.css';

export const metadata: Metadata = {
  title: 'Хакатон Росбанк | Команда 6',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <html lang="ru">
      <body className={`${manrope.variable}`}>{children}</body>
    </html>
  );
};

export default RootLayout;
