MAX_LENGTH_ABOUT_TEAM = 128
MAX_LENGTH_FIRSTNAME = 64
MAX_LENGTH_LASTNAME = 128
MAX_LENGTH_ICON = 128
MAX_LENGTH_KEY_EMPLOYEE = 4
MAX_LENGTH_ROLE = 64
MAX_LENGTH_URL_CONFLUENCE = 128
MAX_LENGTH_URL_JIRA = 128
